browser:
  headless: true
  implicit_wait: 10
  page_load_timeout: 300
  window_height: 10800
  window_width: 19200
linkedin:
  username_display: Ivan Chen
logging:
  file: scraper.log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
search:
  base_url: https://www.linkedin.com/jobs/search/
  filters:
    f_CR: '102890883'
    f_E: 3,4,5,6
    f_F: it
    f_JT: F
    f_TPR: '604800'
    f_WT: '1'
  keywords: ("System"OR"Systems"OR"Software"OR"Engineer"OR"Digital"OR"Partner"OR"Product
    Manager"OR"Owner"OR"HEAD"OR"Lead"OR"Leader"OR"Director"OR"Manager"OR"Application"OR"CIO"OR"AI"OR"Artificial
    Intelligence"OR"Solution")AND("Health"OR"Healthcare"OR"Medical"OR"Medical care"OR"Life
    Science"OR"MedTech"OR"Devices"OR"Business"OR"HCP"OR"Customer"OR"Consumer"OR"Veeva"OR"Salesforce"OR"SFDC"OR"R%26D"OR"Tech")
  results_per_page: 25
  sort_by: R
storage:
  encoding: utf-8-sig
  filename: linkedin_jobs.csv
waits:
  between_pages: 5
  element_wait: 60
  page_load: 300
  verification_retry: 30
